# -*- coding: utf-8 -*-
"""ABC_custChurnRate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9EjNUsQw6Dt4i1E5qNcOSU_9-WV9h7U
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

df.shape

df.info()

df.dtypes

df["Churn"].value_counts(normalize=True)

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'] = df['TotalCharges'].fillna(0)

df = df.drop('customerID', axis=1)

df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

categorical_cols = df.select_dtypes(include='object').columns.tolist()
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
df_encoded.shape

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df_encoded.drop('Churn', axis=1)
y = df_encoded['Churn']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train_scaled, y_train)

from sklearn.metrics import (accuracy_score, classification_report,
                              confusion_matrix, roc_auc_score, RocCurveDisplay)

y_pred = model.predict(X_test_scaled)
y_prob = model.predict_proba(X_test_scaled)[:, 1]

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print(classification_report(y_test, y_pred))

sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted'); plt.ylabel('Actual'); plt.title('Confusion Matrix')
plt.show()

RocCurveDisplay.from_predictions(y_test, y_prob)
plt.show()

cm = confusion_matrix(y_test, y_pred)

fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False, ax=ax)

ax.set_xlabel('Predicted labels')
ax.set_ylabel('True labels')
ax.set_title('Confusion Matrix with Labels')
ax.xaxis.set_ticklabels(['No Churn (0)', 'Churn (1)'], rotation=0)
ax.yaxis.set_ticklabels(['No Churn (0)', 'Churn (1)'], rotation=90)

# Add text annotations for clarity
ax.text(0.5, 0.5, 'True Negatives', ha='center', va='center', color='black', fontsize=12, transform=ax.transAxes)
ax.text(1.5, 0.5, 'False Positives', ha='center', va='center', color='black', fontsize=12, transform=ax.transAxes)
ax.text(0.5, 1.5, 'False Negatives', ha='center', va='center', color='black', fontsize=12, transform=ax.transAxes)
ax.text(1.5, 1.5, 'True Positives', ha='center', va='center', color='black', fontsize=12, transform=ax.transAxes)

# Explicitly add the actual values back to avoid being covered by the labels
for i in range(2):
    for j in range(2):
        ax.text(j + 0.5, i + 0.5, cm[i, j], ha='center', va='center', color='black', fontsize=14, fontweight='bold')

plt.tight_layout()
plt.show()

"""In this confusion matrix:

*   **False Positives (Top Right):** These are cases where the model **predicted Churn (1)**, but the customer **did not actually churn (0)**. These are instances where the model incorrectly flagged a customer as a churn risk.

From the output above, the false positives are the value in the top-right cell. This represents the number of customers who were predicted to churn but actually did not.

### Strategies to Improve Precision

To improve the precision of your model (i.e., reduce False Positives), you can consider the following approaches:

1.  **Adjust the Classification Threshold:**
    *   By default, many classification models use a threshold of 0.5 (if `probability > 0.5`, predict positive). Increasing this threshold will make the model more conservative in predicting the positive class (Churn in this case). This will likely reduce the number of False Positives, thus increasing precision. However, it might also increase False Negatives and reduce recall.

2.  **Feature Engineering and Selection:**
    *   **Add more relevant features:** Are there other data points or characteristics of customers that could strongly indicate churn? Adding these could help the model differentiate better.
    *   **Refine existing features:** Some features might not be contributing effectively or might be noisy. You could try different transformations or combinations of features.
    *   **Remove irrelevant features:** Features that are not strongly correlated with churn or add noise can sometimes hurt precision.

3.  **Explore Different Models:**
    *   While Logistic Regression is a good baseline, more complex models like Gradient Boosting (e.g., XGBoost, LightGBM) or Support Vector Machines (SVMs) might be able to capture more nuanced relationships in the data, potentially leading to better precision.

4.  **Ensemble Methods:**
    *   Combining predictions from multiple models (e.g., Bagging, Boosting, Stacking) can often lead to more robust predictions and better performance metrics like precision.

5.  **Address Class Imbalance (if applicable):**
    *   Although `class_weight='balanced'` was used, which helps, if the imbalance is severe, further techniques like oversampling the minority class (SMOTE) or undersampling the majority class (if data volume allows) could be explored. However, be cautious as these can sometimes lead to overfitting.

6.  **Error Analysis:**
    *   Examine the False Positive cases. What do these customers have in common? Understanding why the model incorrectly predicted them as churners can provide insights into data collection gaps or features that need more attention.

### Next Steps:

If you'd like to explore adjusting the threshold, I can generate code for that, or we can delve into feature engineering.
"""

coef_df = pd.DataFrame({
    'feature': X.columns,
    'coefficient': model.coef_[0]
}).sort_values('coefficient', key=abs, ascending=False)
print(coef_df.head(15))

import joblib
from google.colab import files

joblib.dump(model, 'churn_model.pkl')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(X.columns.tolist(), 'model_columns.pkl')  # so the app can align input columns

files.download('churn_model.pkl')
files.download('scaler.pkl')
files.download('model_columns.pkl')



import streamlit as st
import pandas as pd
import joblib

st.set_page_config(page_title="ABC Ltd. Customer Churn Predictor", layout="centered")

model = joblib.load('churn_model.pkl')
scaler = joblib.load('scaler.pkl')
model_columns = joblib.load('model_columns.pkl')

st.title("📉 ABC Ltd. — Customer Churn Predictor")
st.write("Enter a customer's details to predict their likelihood of churning.")

col1, col2 = st.columns(2)

with col1:
    gender = st.selectbox("Gender", ["Male", "Female"])
    senior = st.selectbox("Senior Citizen", ["No", "Yes"])
    partner = st.selectbox("Has Partner", ["No", "Yes"])
    dependents = st.selectbox("Has Dependents", ["No", "Yes"])
    tenure = st.slider("Tenure (months)", 0, 72, 12)
    phone = st.selectbox("Phone Service", ["No", "Yes"])
    multiple_lines = st.selectbox("Multiple Lines", ["No", "Yes", "No phone service"])
    internet = st.selectbox("Internet Service", ["DSL", "Fiber optic", "No"])
    online_sec = st.selectbox("Online Security", ["No", "Yes", "No internet service"])
    online_backup = st.selectbox("Online Backup", ["No", "Yes", "No internet service"])

with col2:
    device_protect = st.selectbox("Device Protection", ["No", "Yes", "No internet service"])
    tech_support = st.selectbox("Tech Support", ["No", "Yes", "No internet service"])
    streaming_tv = st.selectbox("Streaming TV", ["No", "Yes", "No internet service"])
    streaming_movies = st.selectbox("Streaming Movies", ["No", "Yes", "No internet service"])
    contract = st.selectbox("Contract", ["Month-to-month", "One year", "Two year"])
    paperless = st.selectbox("Paperless Billing", ["No", "Yes"])
    payment = st.selectbox("Payment Method", [
        "Electronic check", "Mailed check",
        "Bank transfer (automatic)", "Credit card (automatic)"
    ])
    monthly_charges = st.number_input("Monthly Charges ($)", 0.0, 200.0, 70.0)
    total_charges = st.number_input("Total Charges ($)", 0.0, 10000.0, 840.0)

if st.button("Predict Churn Risk"):
    input_dict = {
        'gender': gender, 'SeniorCitizen': 1 if senior == "Yes" else 0,
        'Partner': partner, 'Dependents': dependents, 'tenure': tenure,
        'PhoneService': phone, 'MultipleLines': multiple_lines,
        'InternetService': internet, 'OnlineSecurity': online_sec,
        'OnlineBackup': online_backup, 'DeviceProtection': device_protect,
        'TechSupport': tech_support, 'StreamingTV': streaming_tv,
        'StreamingMovies': streaming_movies, 'Contract': contract,
        'PaperlessBilling': paperless, 'PaymentMethod': payment,
        'MonthlyCharges': monthly_charges, 'TotalCharges': total_charges
    }

    input_df = pd.DataFrame([input_dict])
    input_encoded = pd.get_dummies(input_df)

    # Align columns with training data (fill missing dummy cols with 0)
    input_encoded = input_encoded.reindex(columns=model_columns, fill_value=0)

    input_scaled = scaler.transform(input_encoded)
    prediction = model.predict(input_scaled)[0]
    probability = model.predict_proba(input_scaled)[0][1]

    st.divider()
    if prediction == 1:
        st.error(f"⚠️ High Churn Risk — Probability: {probability:.1%}")
    else:
        st.success(f"✅ Low Churn Risk — Probability: {probability:.1%}")

    st.progress(float(probability))
